### ISSUE TITLE
As a user I can login using facebook login so that I don't have to create a new login with goodbyeYall

### ISSUE THREAD

**Issue by Fitzpatrick1** [theTravelingCodesmen/goodbyeYall#65]
Add FB Passport

**Comment by knowrat** [comment]
We'd like for our users to be able to login using facebook and then logout if they desire. The hypothesis is that a significant portion of users don't like creating logins with random sites due to trust issues. Also, it will remove friction in signing up. Lastly, hooking up facebook will enable us to use the social graph for quickly inviting friends to the app should that ever become a need.

Definition of done:
- user can login using facebook
- user can logout
- new/modified tests
- all existing and new tests pass
- documentation, if necessary
- code is reviewed and code reviewer leaves a comment on this issue
- feature is demonstrated to product manager (pm), accepted, and pm leaves a comment on this issue

**Comment by knowrat** [comment]
Something to think about: do we want the user to be logged in next time they visit the site, let's say a day later after they closed their browser? Or do we want to log them out after a certain time? If we remember the user so they don't have to login, how long? 24 hours? 30 days? 365 days? forever?
